### ISSUE TITLE
求助 关于padavan IPv6 内网穿透

### ISSUE THREAD

**Issue by zhu327** [bettermanbao/padavan-shadowsocks-libev#1]
你好bettermanbao, 一直在用你的k2固件, 真的很好用, 最近在折腾移动宽带IPv6 
尝试使用: modprobe ebtable_broute

但是内核模块没有ebtable_broute 
也尝试自己在WSL下编译, 但是没有成功

求助一下, 能不能帮忙编一个, 多谢了

**Comment by allenkey666** [comment]
ip6tables不行？

**Comment by zhu327** [comment]
我找到的解决IPv6内网问题, 都是这样的:

```shell
modprobe ip6table_mangle
modprobe ebtable_broute
ebtables -t broute -A BROUTING -p ! ipv6 -j DROP -i eth2.2
brctl addif br0 eth2.2
```

原谅我不懂网络, 只能找点资料, 求指导ip6tables怎么用啊

```shell
ip6tables -t nat -A POSTROUTING -o eth2.2 -j MASQUERADE
```

上面的可以嘛
